### ISSUE TITLE
PoB import via Pastebin

### ISSUE THREAD

**Issue by aleskozina** [karakasis/Path-of-Leveling#3]
Hey Dude

Wanted to try your tool and tried to import a PoB link. Did not work. Here are the details:
PoB Version: 1.4.126
PoL version: 65-alpha
pastebin: https://pastebin.com/rhnbd94h

Worked on https://poe.technology/poebuddy/rhnbd94h

Just wanted to inform you!

kr

**Comment by karakasis** [comment]
Hello, if you tried to import a Pastebin that contains a Path of Building file via Import ..
**it will not work**.
This application loads its own files. You can import pastebin's that contain a Path of Leveling file, either ### created by you within the editor, or distributed by someone else in the community.
If you wish to simply **link** your Path of Build file with a certain build, please **use option Path of Building> Link active build with POB**. Once you have done this you can _share your Path of Leveling build buy exporting it to Pastebin_. The new Pastebin link will contain both of the "files" and it can only be opened with Path of Leveling. Thank you.

**Comment by aleskozina** [comment]
Oh, i'm very sorry. 

I misunderstood this feature. I thought i can import gems, trees, etc from a PoB configuration.

Thanks for clarification!

kr
