### ISSUE TITLE
Cant "import" link from pob

### ISSUE THREAD

**Issue by kharom1** [karakasis/Path-of-Leveling#48]
Hi, i have problem with importing pastebin code to PoL i am clicking Path of Building then Create build from Pastebin pasting pob link and clicking Fetch nothing happens.
I have the latest version.

**Comment by karakasis** [comment]
Fixed in version https://github.com/karakasis/Path-of-Leveling/releases/tag/v0.72-beta

**Comment by Razunter** [comment]
nvm, everything works

**Comment by kharom1** [comment]
<3
