### ISSUE TITLE
Gem overlay not showing

### ISSUE THREAD

**Issue by r0bo7** [karakasis/Path-of-Leveling#6]
The gem overlay wont show, even when I press the overlay hotkey. The rest work fine. This is happening maybe because my resolution is ultra wide (2560x1080). The gem overlay window has no content, as seen in the bottom when I put the mouse over its window, but the other windows content is shown.

![image](https://user-images.githubusercontent.com/23621201/51445921-6b05a300-1ce9-11e9-9c1d-4260f0b20709.png)

Also thanks for this amazing tool!

**Comment by r0bo7** [comment]
Now the overlay decided to show after level 8. Just a suggestion: maybe try to compact the information displayed in the gem overlay to fit more info and allow better reading. For example when reaching a6 and doing the fallen from grace quest, generally there is a ton of gems to buy

**Comment by karakasis** [comment]
Hey thanks for the feedback. I believe that that gem showed up at level 8 because that is the first level that you had planned for gems.
