### ISSUE TITLE
Make gems pop up when they become available, not when character reaches the level req (or make this an option)

### ISSUE THREAD

**Issue by lotusmonk** [karakasis/Path-of-Leveling#64]
For example, I'm hoping to be reminded to pick up frostbomb right after Hailrake, not when I hit level 4 while inside the submerged caverns. 

I also can't seem to make "next gem" "previous gem" hotkeys work. I bind the keys and they don't do anything. Are those meant to show the next/previous gems on the list?

**Comment by karakasis** [comment]
Since there is no API provided by GGG that can track quests, you can't know when a player has completed the quest that rewards a certain gem. The only way to achieve it is from the players level for now.

**Comment by karakasis** [comment]
The next/previous is used to swap between gems for a certain level. For example, assume at level 4 you get 3 different gems, only 1 of them will show in the overlay and to change to the other 2 you can use the keybinds. This is done to avoid visual clutter.
