### ISSUE TITLE
Zone Overlay re-positions itself back to default when changing zones

### ISSUE THREAD

**Issue by DerpaholicRex** [karakasis/Path-of-Leveling#65]
When changing zones, if the zone overlay has been moved to an alternate location, it is fading out and fading back in at the default y position for me (x is preserved)

E.G I prefer to have it at the bottom between health and mana, but it kept re-loading up top

I was able to fix by pulling the source and adding a 
if(!isVisible) {
                showPanel();
 }
check to the zone overlay stage queue method (preventing reloading the view, and just updating the images).

The real problem appears to be that the slide in animation has a fixed ending position of 0, and over writes the actual y position as it goes.

This could probably be fixed by setting the current y position as the fade-in target. But that seems more complicated so i'm just used the conditional above for now
It seems like this is not intended behavior, so i wanted to bring it up

**Comment by karakasis** [comment]
Hey, thanks for reporting that. I will have to take a look at it, when I start working on the project again, at summer. The slide animations are not well done, the fade in/out should work though, and preserve your desired position
