### ISSUE TITLE
Request: please support korean client

### ISSUE THREAD

**Issue by Eyeof** [karakasis/Path-of-Leveling#66]
idk why doesn't work on korean client but,
it's all the same as international client just the file name is different.
PathOfExile_KG.exe / PathOfExile_x64_KG.exe 

Is it not working because the file name is different?

**Comment by karakasis** [comment]
I think there is an issue with the Client.txt in any language other than English. It will take some Korean Speaker or w/e other language to actually make such change

**Comment by Eyeof** [comment]
you're right. It works well in english version.
i think the name of the zone translated into korean is the problem.
so i'll just stick with english version.
