### ISSUE TITLE
Suggestions/feedback

### ISSUE THREAD

**Issue by jnitis** [karakasis/Path-of-Leveling#7]
Hi,

Love this program, fantastic idea.  So much better than keeping the info open on my second monitor.  It really made my leveling experience far more enjoyable and helped to teach me more about the game in general.  I have some feedback and I'm not sure if this is the proper place but here goes.  There's **a lot** here so please don't take it in a negative way, I'm just so enthused about the app I thought of many suggestions. :-)

Needs 1440p default x/y support upon detection.  Can I help you with this in any way?

Gem draw routine seemed to not work properly for me most of the time.  It will draw the gem info properly but then either a) leave it on screen way past the timeout or b) collapse it incorrectly so you can still see about 25% of the window.

Is there any way to minimize to systray and/or make it only show up as one window in the task tray?

Add option to bring up settings while app is already running.  Could be via right-click task/systray.

Option (also via right-click) to restart app.  (I had to do this many times manually until things were working in a stable fashion.)

Add ability to specify leveling gear changes as well (weap/armor).

Auto-load most recently used profile on startup.

Either note that character name needs to be case sensitive or make it so it doesn't need to be case sensitive.

Auto-select current character level by query API / read Client.txt file and look for most recent info.  If user enters lower level number manually warn user and ask if he/she is sure.

Regarding the profile editor:

Searching for anything should show the results of that search and that search only.  Preferably all results from all acts in one place.

If there's only one result of the search the item should be auto-selected.

When you create a new gem group it should automatically bring up the attached window.

When you search it would be nice to have live as-you-type results.

Add option to show all gems for each level on multiple lines without having to scroll right/left.

Add tooltips for duplicate group/note buttons.

Auto-select the first non-support gem entered for each group as the default main gem, user can change later.

**Comment by karakasis** [comment]
Thank you for the feedback! Unfortunatelly I am busy at this time with school, and I won't be able to work on this for a while. I will try and include some of your suggestions if possible when I find some free time .

**Comment by karakasis** [comment]
Hey, im reading through your list and trying to include some requests. What do you mean by restart application? Im trying to think of something else that has that but i cant recall of anything.

**Comment by jnitis** [comment]
Hi, great to hear you have a little free time!

I was thinking along the lines of Poe trade macro where you can right click 
its icon in the systray and there's an option named "reload all (only use 
this)" It's very handy when you make some changes that need an app restart. 
Thanks!

**Comment by karakasis** [comment]
I managed to recruit a couple of people to help on the project and hopefully we can make things happen. and faster. Also i dont know if you have any coding knowledge but if you wanna help on testing the overlays on your 1440p monitor you can join my discord as a tester. I ll leave you my profile. rainy#1844
