### ISSUE TITLE
Editor Window Resizing

### ISSUE THREAD

**Issue by Lothrik** [karakasis/Path-of-Leveling#8]
It would be awesome if resizing the editor window also resized the elements inside. Scrollbars for everything seems a bit silly when the window only takes up 1/4th of my screen.

Edit: Gem searching could use some work too, you can't search for support gems specifically or remove gems from a group once they're added. Gem selection in general is just kinda bad, it would be faster to literally just type in the full gem name.

Edit 2: The list of gems is also extremely inefficient from a CPU perspective -- javaw.exe goes from 0.03% to 5% just having the skill gem list open, and actually scrolling through a list pushes it to 25% (100% single core).

**Comment by karakasis** [comment]
Hey thanks for the feedback. I will try and look into it, especially the cpu hungry code i wrote. If you can code add me on Discord, since im not sure how to fix that !

**Comment by karakasis** [comment]
In the next update you can resize the app. It wont make the icons or text bigger, but it should eliminate the scrolling on some stuff, and make the browsing smoother. 
Gem searching has also been added, including auto-complete . 
" Remove gems from a group once they are added " have you tried selecting the gem and clicking the '-' icon (remove) ?
Gem selection is being planned to improve even more by adding gem tag filtering etc.
